### PR TITLE
add juniper logo

### PR DESCRIPTION
**Pull request by fischa**
I stumbled across this great repo of vendor icons and didn't see juniper in here. Please add.

### CODE REVIEW

**Comment by bwks** [comment]
Awesome thank you for this :) I'll look to merge it in when I get home!

**Comment by fischa** [comment]
@bobthebutcher is there an issue with my PR? Let me know if you need/want something changed.

**Comment by bwks** [comment]
> 
> 
> @bobthebutcher is there an issue with my PR? Let me know if you need/want something changed.

No issues sorry, just have not had time to look at it at the moment.

**Comment by bwks** [comment]
Looks good @fischa . Thanks for you contribution.

**Pull request merged**
